engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  tslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
    - 'projects/ng-dynamic-component/src/lib/**/*.ts'
exclude_patterns:
  - '**.*'
  - '!projects/ng-dynamic-component/src/lib/**/*.ts'
