sudo: required
dist: trusty
language: node_js
cache:
  npm: true
notifications:
  email: false
node_js: lts/*
stages:
  - test
  - name: deploy
    if: branch = master and type != pull_request
jobs:
  include:
    - stage: test
      script:
        - npm run build
        - npm run format:check
        - npm run lint
        - npm run test:ci
        - npm run coverage:check
        - npm run test:report
    - stage: release
      script:
        - npm run build
        - npm run pack
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run semantic-release
